// ─── Edit your bingo squares here ───────────────────────────────────────────
// Add, remove, or rename any square. The free space is handled separately
// in index.html and will always stay in the center. You need at least 24
// squares to fill a 5×5 board (the 25th spot is the Free Space).

window.BINGO_SQUARES_ANNALINA = [
  "Freezer Kits",
  "Classic Annalina Fit :)",
  "Lab Accident",
  "Day 1 IHC Staining",
  "Microtome Use (Payton)",
  "Day 1 LFB Staining",
  "Jobs for Other Labs",
  "Embedding",
  "Scavenge for Food with Randy",
  "Spotify in Lab",
  "Microscope w/ Randy",
  "More than 2 Pairs of Gloves",
  "Visiopharm",
  "Slide Cleaning",
  "Day 2 IHC Staining",
  "Attend a Seminar",
  "Brain Autopsy w/ Randy",
  "Use of Database / Slide Scanning / Pathology",
  "Cover Slipping",
  "Slide Labelling",
  "Shenanigans w/ Payton",
  "Block/Slide Filing",
  "Drive the Mustang",
  "Day 2 LFB Staining",
  "Uses Yurt Emoji",
];

// ─── Pretham's squares ───────────────────────────────────────────────────────
window.BINGO_SQUARES_PRETHAM = [
  "Passion Project",
  "Wears Tshorts",
  "Investing / Make a Trade",
  "Board Games",
  "Listen to Lil Tecca",
  "Facetime Lovely Girlfriend",
  "Hack into Mainframe (use terminal)",
  "Bug in Code",
  "Touch Grass",
  "Fills Water Bottle 2x",
  "Work Email",
  "Protein Milk",
  "Vibe Code",
  "Freshly Shorn",
  "Read a Book",
  "Eat Dosa",
  "See an NBA Tweet",
  "Video Gaming",
  "Dheeraj Moment",
  "Unproductive YouTube Video",
  "Villa Sport",
  "College Apps",
  "Knee Isometric",
  "To-Do List",
  "Ran Out of Claude Credits",
  "Uses Yurt Emoji",
];
